Module one capston project final
aster-alemu/ModuleOneCapston pull request #1
Opened 2022-05-27 15:46 UTC by aster-alemu

In this PR, I have been doing the following activities

1. Create repository
2. Clone the remote repo to local machine
3. Create branch repository
4. Create mobile version for the home and about page
5. Then create a desktop version for the two page
6. Fix Eslint andd Stylelint errors
7. Record a video using loom
8. Add and commit the files

2022-05-27 16:33 UTC, CollinsTatang requested changes
Hi @aster-alemu , 

Good job so far!
There are some issues that you still need to work on to go to complete this project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 16:33 UTC, CollinsTatang commented on index.html
> +           <a href="index.html"><img src="image/logo.png" alt=""></a>
- [ ] Please kindly fix the routes to your different images. The image link generates an error due to the wrong directory name so please change `image` to `Image`.

2022-05-27 16:33 UTC, CollinsTatang commented on index.html
> +        </div>
- [ ] Nice implementation of the main section of your app but you still need to work on your design to meet that of the required design.
![main](https://user-images.githubusercontent.com/55596970/170737610-fe1b4076-bd2a-4ef4-8507-af43936efc0d.png)
### **Your design**
![yourMain](https://user-images.githubusercontent.com/55596970/170738210-f2fbe82d-1167-4ddf-938d-f41011820923.png)

2022-05-27 16:33 UTC, CollinsTatang commented on index.html
> +      </section>
- [ ] Nice implementation of the feature section of your app but you still need to work on your design to meet the [required design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
### **Your design**
![feat](https://user-images.githubusercontent.com/55596970/170739174-463dd2d2-3e40-4258-b82f-a4ffea2be417.png)

2022-05-27 16:33 UTC, CollinsTatang commented on index.html
> +      </footer>
- [ ] Please try to center the footers design to meet the [required design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

2022-05-27 16:33 UTC, CollinsTatang commented on about.html
> +      </div>
- [ ] Please kindly fix the design of this section to meet the required project design [required project design ](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
### **Your design**
![screen](https://user-images.githubusercontent.com/55596970/170740960-fa411865-0371-47e1-82ca-0d7b9a2a8858.png)

2022-05-28 12:05 UTC, codepantha approved these changes
Hi @aster-alemu 👋,

## STATUS: APPROVED ✔️  

Well done implementing all the required changes 👏 
Your project is now complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Meaningful Commit messages
✔️ Linter checks

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 12:05 UTC, codepantha commented on README.md
> +## 📝 License
- [ ] [Optional] This requirement is marked OPTIONAL because the previous reviewer skipped it, but please it's quite important that you acknowledge and give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

- [ ] [Optional] This is marked OPTIONAL for the same reason given above ☝️. Please include the link to your live app deployed with Github pages in your README file. This is an important requirement.

2022-05-28 12:08 UTC, merged